# Configuração do Easypanel para o ProjectManager

# Configuração principal
name: projectmanager
domain: projectmanager.local
compose_file: docker-compose.yml

# Configurações específicas para serviços expostos
services:
  web:
    external_port: 3000
    expose: true
    path: /
  
  api:
    external_port: 3001
    expose: true
    path: /api
  
  plane:
    external_port: 3000
    expose: true
    path: /plane
  
  outline:
    external_port: 3001
    expose: true
    path: /outline

# Desabilitar a geração automática do NGINX
disable_nginx: true 