version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projectmanager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  api:
    build:
      context: ./packages/api
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/projectmanager
      JWT_SECRET: your_jwt_secret_here
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm start"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=3001"

  web:
    build:
      context: ./packages/web
    restart: always
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: /api
      NEXT_PUBLIC_PLANE_URL: /plane
      NEXT_PUBLIC_OUTLINE_URL: /outline
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"

  plane:
    build:
      context: ./packages/plane
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plane.rule=PathPrefix(`/plane`)"
      - "traefik.http.services.plane.loadbalancer.server.port=3000"

  outline:
    build:
      context: ./packages/outline
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.outline.rule=PathPrefix(`/outline`)"
      - "traefik.http.services.outline.loadbalancer.server.port=3001"

  # Serviço vazio para substituir o NGINX do Easypanel
  nginx:
    image: alpine:latest
    command: ["sh", "-c", "echo 'NGINX desabilitado' && sleep infinity"]
    restart: "no"
    labels:
      - "traefik.enable=false"
    deploy:
      replicas: 0

volumes:
  postgres_data: 