version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projectmanager
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - api_data:/app/data
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/projectmanager
      JWT_SECRET: your_jwt_secret_here
      PLANE_API_KEY: your_plane_api_key
      OUTLINE_API_KEY: your_outline_api_key
    expose:
      - "3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: >
      sh -c "npx prisma generate && npx prisma migrate deploy && npm run db:seed && npm start"

  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - web_data:/app/data
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: /api
      NEXT_PUBLIC_PLANE_URL: /plane
      NEXT_PUBLIC_OUTLINE_URL: /outline
    expose:
      - "3000"
    depends_on:
      - api
    networks:
      - app-network

  plane:
    build:
      context: ./packages/plane
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - app-network

  outline:
    build:
      context: ./packages/outline
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3001"
    networks:
      - app-network

volumes:
  postgres_data:
  api_data:
  web_data:

networks:
  app-network:
    driver: bridge 