version: '3.8'

# Este arquivo é usado para sobrescrever e estender as configurações do docker-compose.yml
# Aqui estamos configurando explicitamente nossos serviços para o ambiente Easypanel

services:
  # Configuração principal para web (frontend)
  web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.routers.web.entrypoints=web"
    ports:
      - "3000"

  # Configuração para API
  api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=3001"
      - "traefik.http.routers.api.entrypoints=web"
    ports:
      - "3001"

  # Configuração para Plane
  plane:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plane.rule=PathPrefix(`/plane`)"
      - "traefik.http.services.plane.loadbalancer.server.port=3000"
      - "traefik.http.routers.plane.entrypoints=web"
    ports:
      - "3000"

  # Configuração para Outline
  outline:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.outline.rule=PathPrefix(`/outline`)"
      - "traefik.http.services.outline.loadbalancer.server.port=3001"
      - "traefik.http.routers.outline.entrypoints=web"
    ports:
      - "3001"

  # Desabilitando explicitamente o NGINX caso ele seja injetado pelo Easypanel
  nginx:
    image: hello-world
    command: ["echo", "NGINX desabilitado - usando o proxy reverso do Easypanel"]
    restart: "no"
    labels:
      - "traefik.enable=false"
    deploy:
      replicas: 0 