version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: projectmanager_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projectmanager
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    image: projectmanager-api:latest
    container_name: projectmanager_api
    restart: unless-stopped
    volumes:
      - api_data:/app/data
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/projectmanager
      JWT_SECRET: your_jwt_secret_here
      PLANE_API_KEY: your_plane_api_key
      OUTLINE_API_KEY: your_outline_api_key
    expose:
      - "3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: >
      sh -c "yarn db:migrate && yarn db:seed && yarn start"

  web:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    image: projectmanager-web:latest
    container_name: projectmanager_web
    restart: unless-stopped
    volumes:
      - web_data:/app/data
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://api:3001
    expose:
      - "3000"
    depends_on:
      - api
    networks:
      - app-network

  plane:
    build:
      context: ./packages/plane
      dockerfile: Dockerfile
    image: projectmanager-plane:latest
    container_name: projectmanager_plane
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - app-network

  outline:
    build:
      context: ./packages/outline
      dockerfile: Dockerfile
    image: projectmanager-outline:latest
    container_name: projectmanager_outline
    restart: unless-stopped
    expose:
      - "3001"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: projectmanager_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    labels:
      - "easypanel.publish=true"
      - "easypanel.port=8080"
    depends_on:
      - web
      - api
      - plane
      - outline
    networks:
      - app-network

volumes:
  postgres_data:
  api_data:
  web_data:

networks:
  app-network:
    driver: bridge 