version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "${POSTGRES_PORT:-9432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: projectmanager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  api:
    build:
      context: ./packages/api
    restart: always
    environment:
      NODE_ENV: production
      PORT: ${API_PORT:-9001}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/projectmanager
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_here}
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm start"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=${API_PORT:-9001}"

  web:
    build:
      context: ./packages/web
    restart: always
    environment:
      NODE_ENV: production
      PORT: ${WEB_PORT:-9004}
      NEXT_PUBLIC_API_URL: /api
      NEXT_PUBLIC_PLANE_URL: /plane
      NEXT_PUBLIC_OUTLINE_URL: /outline
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.services.web.loadbalancer.server.port=${WEB_PORT:-9004}"

  plane:
    build:
      context: ./packages/plane
    restart: always
    environment:
      PORT: ${PLANE_PORT:-9002}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plane.rule=PathPrefix(`/plane`)"
      - "traefik.http.services.plane.loadbalancer.server.port=${PLANE_PORT:-9002}"

  outline:
    build:
      context: ./packages/outline
    restart: always
    environment:
      PORT: ${OUTLINE_PORT:-9003}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.outline.rule=PathPrefix(`/outline`)"
      - "traefik.http.services.outline.loadbalancer.server.port=${OUTLINE_PORT:-9003}"

  # Serviço vazio para substituir o NGINX do Easypanel
  nginx:
    image: alpine:latest
    command: ["sh", "-c", "echo 'NGINX desabilitado' && sleep infinity"]
    restart: "no"
    labels:
      - "traefik.enable=false"
    deploy:
      replicas: 0

volumes:
  postgres_data: 