version: '3.8'

services:
  nginx:
    ports:
      - "${HTTP_PORT:-8800}:80"
      - "${HTTPS_PORT:-8443}:443"
    environment:
      - VIRTUAL_HOST=${DOMAIN:-localhost}
      - LETSENCRYPT_HOST=${DOMAIN:-localhost}
      - LETSENCRYPT_EMAIL=${EMAIL:-admin@example.com}
    
  api:
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    
  web:
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://${DOMAIN:-localhost}:${HTTPS_PORT:-8443}/api 