services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_MULTIPLE_DATABASES: projectmanager,outline
    ports:
      - "${POSTGRES_PORT:-9432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Redis para cache e sessões
  redis:
    image: redis:6-alpine
    ports:
      - "${REDIS_PORT:-9379}:6379"
    volumes:
      - redis-data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # Serviço da API integrada
  api:
    build:
      context: ../packages/api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/projectmanager
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-seu_jwt_secret_seguro_aqui}
      PORT: ${API_PORT:-9001}
      PLANE_URL: http://plane:${PLANE_PORT:-9002}
      OUTLINE_URL: http://outline:${OUTLINE_PORT:-9003}
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - internal

  # Serviço Plane
  plane:
    build:
      context: ../packages/plane
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/projectmanager
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-seu_jwt_secret_seguro_aqui}
      PORT: ${PLANE_PORT:-9002}
      API_URL: http://api:${API_PORT:-9001}
    restart: always
    depends_on:
      - postgres
      - redis
      - api
    networks:
      - internal

  # Serviço Outline modificado
  outline:
    build:
      context: ../packages/outline
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/outline
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-seu_jwt_secret_seguro_aqui}
      PORT: ${OUTLINE_PORT:-9003}
      API_URL: http://api:${API_PORT:-9001}
      SECRET_KEY: ${SECRET_KEY:-seu_secret_key_seguro_aqui}
    restart: always
    depends_on:
      - postgres
      - redis
      - api
    networks:
      - internal

  # Frontend (UI)
  web:
    build:
      context: ../packages/web
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: ${WEB_PORT:-9004}
      # URLs internas para a comunicação dentro da rede Docker
      NEXT_PUBLIC_API_URL: /api
      NEXT_PUBLIC_PLANE_URL: /
      NEXT_PUBLIC_OUTLINE_URL: /docs
    restart: always
    depends_on:
      - api
      - plane
      - outline
    networks:
      - internal

  # Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    ports:
      - "${HTTP_PORT:-9080}:80"
      - "${HTTPS_PORT:-9443}:443"
    volumes:
      - ../infra/nginx/projectmanager.conf:/etc/nginx/conf.d/default.conf
      - ../infra/nginx/ssl:/etc/nginx/ssl
      - static-data:/var/www/html
    restart: always
    depends_on:
      - web
      - api
      - plane
      - outline
    networks:
      - internal
      - external

volumes:
  postgres-data:
  redis-data:
  static-data:

networks:
  internal:
    internal: true
  external:
    driver: bridge 