version: '3.8'

services:
  nginx:
    ports:
      - "${HTTP_PORT:-9080}:80"
      - "${HTTPS_PORT:-9443}:443"
    environment:
      - VIRTUAL_HOST=${DOMAIN:-localhost}
      - LETSENCRYPT_HOST=${DOMAIN:-localhost}
      - LETSENCRYPT_EMAIL=${EMAIL:-admin@example.com}
    
  api:
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - PORT=${API_PORT:-9001}
    
  web:
    environment:
      - NODE_ENV=production
      - PORT=${WEB_PORT:-9004}
      - NEXT_PUBLIC_API_URL=https://${DOMAIN:-localhost}:${HTTPS_PORT:-9443}/api
      
  plane:
    environment:
      - PORT=${PLANE_PORT:-9002}
      
  outline:
    environment:
      - PORT=${OUTLINE_PORT:-9003} 